language: node_js
node_js:
- "stable"
install:
  - npm install
script:
  - npm test
  - npm run coverage
env:
  - NODE_ENV=test
cache:
  directories:
    - "node_modules"
after_success :
    - npm run coverage
